#!/usr/bin/env bash
#
# Convert BMPs under assets/bmp/ to PNGs and embed them as C byte arrays
# in assets/textures.c (with a matching assets/textures.h).
#
# Dependencies (one of, in order of preference):
#   * sips         (preinstalled on macOS)
#   * magick       (ImageMagick 7)
#   * convert      (ImageMagick 6)
# Plus: xxd (vendored with vim; preinstalled on macOS and most Linux distros).
#
# Re-run is cheap: PNGs and the generated C are skipped when newer than
# their inputs, so this is safe to call from `make` on every build.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ASSETS="${REPO_ROOT}/assets"
BMP_DIR="${ASSETS}/bmp"
PNG_DIR="${ASSETS}/png"
TEX_C="${ASSETS}/textures.c"
TEX_H="${ASSETS}/textures.h"

mkdir -p "${PNG_DIR}"

if   command -v sips    >/dev/null 2>&1; then CONVERT=sips
elif command -v magick  >/dev/null 2>&1; then CONVERT=magick
elif command -v convert >/dev/null 2>&1; then CONVERT=convert
else
  echo "embed-textures: need sips, magick, or convert in PATH" >&2
  exit 1
fi

if ! command -v xxd >/dev/null 2>&1; then
  echo "embed-textures: need xxd in PATH" >&2
  exit 1
fi

bmp_to_png() {
  local bmp="$1" png="$2"
  case "${CONVERT}" in
    sips)    sips -s format png "${bmp}" --out "${png}" >/dev/null ;;
    magick)  magick "${bmp}" "${png}" ;;
    convert) convert "${bmp}" "${png}" ;;
  esac
}

# Stable build symbol from a filename stem ("1" -> "tex_1", "floor" -> "tex_floor").
sym_for() {
  local stem="$1"
  printf 'tex_%s' "$(printf '%s' "${stem}" | tr -c 'A-Za-z0-9_' '_')"
}

# Convert each BMP to PNG (skip if up-to-date).
shopt -s nullglob
bmps=("${BMP_DIR}"/*.bmp)
if [ "${#bmps[@]}" -eq 0 ]; then
  echo "embed-textures: no .bmp files in ${BMP_DIR}" >&2
  exit 1
fi

for bmp in "${bmps[@]}"; do
  stem="$(basename "${bmp}" .bmp)"
  png="${PNG_DIR}/${stem}.png"
  if [ ! -f "${png}" ] || [ "${bmp}" -nt "${png}" ]; then
    echo "  PNG    ${stem}.png"
    bmp_to_png "${bmp}" "${png}"
  fi
done

# Skip regenerating C if every PNG is older than the existing .c.
need_regen=0
if [ ! -f "${TEX_C}" ] || [ ! -f "${TEX_H}" ]; then
  need_regen=1
else
  for png in "${PNG_DIR}"/*.png; do
    if [ "${png}" -nt "${TEX_C}" ]; then need_regen=1; break; fi
  done
fi

if [ "${need_regen}" -eq 0 ]; then
  echo "  CACHE  assets/textures.{c,h} up to date"
  exit 0
fi

# Generate textures.h
{
  printf '/* Generated by scripts/embed-textures.sh. Do not edit. */\n'
  printf '#ifndef ASSETS_TEXTURES_H\n#define ASSETS_TEXTURES_H\n\n'
  printf '#ifdef __cplusplus\nextern "C" {\n#endif\n\n'
  for png in "${PNG_DIR}"/*.png; do
    stem="$(basename "${png}" .png)"
    sym="$(sym_for "${stem}")"
    printf 'extern const unsigned char %s[];\n' "${sym}"
    printf 'extern const unsigned int  %s_len;\n' "${sym}"
  done
  printf '\n#ifdef __cplusplus\n}\n#endif\n\n#endif\n'
} > "${TEX_H}"

# Generate textures.c
{
  printf '/* Generated by scripts/embed-textures.sh. Do not edit. */\n'
  printf '#include "textures.h"\n\n'
  for png in "${PNG_DIR}"/*.png; do
    stem="$(basename "${png}" .png)"
    sym="$(sym_for "${stem}")"
    printf 'const unsigned char %s[] = {\n' "${sym}"
    xxd -i < "${png}" | sed 's/^/    /'
    printf '};\n'
    printf 'const unsigned int %s_len = sizeof(%s);\n\n' "${sym}" "${sym}"
  done
} > "${TEX_C}"

echo "  GEN    assets/textures.c (${#bmps[@]} textures, $(wc -c <"${TEX_C}" | tr -d ' ') bytes)"
echo "  GEN    assets/textures.h"
